#:schema node_modules/wrangler/config-schema.json
name = "wp-star"
main = "src/index.ts"
compatibility_date = "2024-06-05"
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "josh412-cdn-1"
preview_bucket_name = "cdn-dev"
