name = "joshdata"
main = "src/worker.ts"
compatibility_date = "2023-08-21"

[[kv_namespaces]]
binding = "KV"
id = "419991e62cdd45e6b1acbc45fadf0204"
preview_id = "c00a0570cd4b4f0083936400ef3b77d0"

[[d1_databases]]
binding = "DB1"
database_name = "josh412-dgb"
database_id = "8c72c8d9-c20f-44d2-88e9-c65b787a6495"

[[r2_buckets]]
binding = "DATABUCKET"
bucket_name = "joshdata"
preview_bucket_name= "joshdatalocal"
