name = "scheduler"
main = "src/index.ts"
compatibility_date = "2023-10-16"

## buckets
[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "scheduler-media-00"
preview_bucket_name = "scheduler-media-00-prev"
