name = "feeder-api"
main = "src/index.ts"
compatibility_date = "2023-10-30"


[[d1_databases]]
binding = "DB"
database_name = "feeder-01"
database_id = "24c22221-e1e0-4e9e-bc3e-6a72a95f60e9"
migrations_table = "d1_migrations" # Customize this value to change your applied migrations table name
migrations_dir = "migrations"

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "scheduler-media-00"
preview_bucket_name = "scheduler-media-00-prev"


## KV namespaces
[[kv_namespaces]]
binding = "KV"
id = "3f74d87bb28c49b5b2ceca3670830dae"
preview_id = "ac56430781d647dc84d18f8cdb36c6cc"
