name = "cdn"
main = "src/worker.ts"
compatibility_date = "2023-08-21"

[vars]
AUTH_SECRET = "9b88b17f4abfdb870e1ac42"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "josh412-cdn-1"
preview_bucket_name= "josh412-cdn-1-local"
