name = "cdn"
main = "src/index.ts"
compatibility_date = "2023-08-21"
usage_model = "unbound"
env = { }

[triggers]
crons = [ ]



[[r2_buckets]]
binding = "BUCKET"
bucket_name = "josh412-cdn-1"
preview_bucket_name = "cdn-dev"
