name = "cdn"
main = "src/index.ts"
compatibility_date = "2023-08-21"
usage_model = "unbound"
env = { }

[triggers]
crons = [ ]

[vars]
AUTH_SECRET = "9b88b17f4abfdb870e1ac42"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "josh412-cdn-1"
