name = "josh412-site"
main = "src/server.ts"
compatibility_date = "2023-09-20"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "dist"

[build]
cwd = "dist"
watch_dir = "src"


[[d1_databases]]
binding = "DB"
database_name = "josh412-02"
database_id = "06b68e8f-0a21-42d6-9673-6dfffabfd1c0"
migrations_table = "d1_migrations" # Customize this value to change your applied migrations table name
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "57f0bd6a06dd4e2287d18fb4360adb5b"
