name: Workers

on: [push]

jobs:
  paths-filter:
      runs-on: ubuntu-latest
      outputs:
        joshdata: ${{ steps.filter.outputs.joshdata }}
        wordpressproxy: ${{ steps.filter.outputs.wordpressproxy }}
        cdn: ${{ steps.filter.outputs.cdn }}
      steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            cdn:
              - 'workers/cdn/**'
            joshdata:
              - 'workers/joshdata/**'
            wordpressproxy:
              - 'workers/wordpress-proxy/**'

      # run only if 'cdn' files were changed
      - name: cdn changed
        if: steps.filter.outputs.cdn == 'true'
        run: echo "cdn changed"

      # run only if 'joshdata' files were changed
      - name: joshdata changed
        if: steps.filter.outputs.joshdata == 'true'
        run: echo "joshdata changed"

      # run only if 'wordpressproxy' files were changed
      - name: wordpress proxy changed
        if: steps.filter.outputs.wordpressproxy == 'true'
        run: echo "wordpress proxy changed"

  cdn:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.cdn == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: install cdn
        run: npm i
        working-directory: workers/cdn

      - name: Deploy
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        working-directory: workers/cdn


  wordpressproxy:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.wordpressproxy == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: install cdn
        run: npm i
        working-directory: workers/wordpress-proxy

      - name: Deploy
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        working-directory: workers/wordpress-proxy
